# Generated by Django 6.0.7 on 2026-08-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="ai_model",
            field=models.CharField(default="dev-mock", max_length=100),
        ),
        migrations.AddField(
            model_name="workspace",
            name="ai_provider",
            field=models.CharField(default="simulated", max_length=100),
        ),
    ]
