# Generated by Django 6.0.7 on 2026-08-17 20:10

from django.db import migrations


def seed_default_agents(apps, schema_editor):
    Agent = apps.get_model('task', 'Agent')
    
    # Create Research Agent
    Agent.objects.get_or_create(
        name="Research Agent",
        defaults={
            "description": "Research and explain concepts.",
            "provider": "simulated",
            "model": "dev-mock",
            "capabilities": ["research"],
            "status": "ACTIVE"
        }
    )
    
    # Create Math Agent
    Agent.objects.get_or_create(
        name="Math Agent",
        defaults={
            "description": "Solves arithmetic tasks.",
            "provider": "simulated",
            "model": "dev-mock",
            "capabilities": ["math"],
            "status": "ACTIVE"
        }
    )

    # Create General Agent
    Agent.objects.get_or_create(
        name="General Agent",
        defaults={
            "description": "Answers general questions.",
            "provider": "simulated",
            "model": "dev-mock",
            "capabilities": ["general"],
            "status": "ACTIVE"
        }
    )

def remove_default_agents(apps, schema_editor):
    Agent = apps.get_model('task', 'Agent')
    Agent.objects.filter(name__in=["Research Agent", "Math Agent", "General Agent"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_agents, reverse_code=remove_default_agents),
    ]
