# Generated by Django 6.0.7 on 2026-08-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_userprovidercredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
