# Generated by Django 6.0.7 on 2026-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_workspacerequest_workspacenotification_requestevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_REQUEST", "New Request"),
                    ("REQUEST_ESCALATED", "Request Escalated"),
                    ("REQUEST_APPROVED", "Request Approved"),
                    ("REQUEST_REJECTED", "Request Rejected"),
                    ("REQUEST_CANCELLED", "Request Cancelled"),
                    ("REQUEST_COMPLETED", "Request Completed"),
                    ("REQUEST_FAILED", "Request Failed"),
                    ("GENERAL", "General Notification"),
                ],
                default="GENERAL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workspacerequest",
            name="decision_status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("ESCALATED", "Escalated"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SUBMITTED",
                max_length=50,
            ),
        ),
    ]
