# Generated by Django 6.0.7 on 2026-09-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0009_alter_workspacenotification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="execution_type",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("RETRY", "Retry"),
                    ("FOLLOW_UP", "Follow Up"),
                ],
                default="INITIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="parent_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_executions",
                to="task.taskexecution",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
